ALTER TABLE student ALTER COLUMN birthday SET NOT NULL;

ALTER TABLE mark ALTER COLUMN student_id SET NOT NULL;
ALTER TABLE mark ALTER COLUMN subject_id SET NOT NULL;
ALTER TABLE mark ALTER COLUMN mark ADD CHECK (mark>=1 AND mark<=10);

ALTER TABLE subject ALTER COLUMN grade ADD CHECK (grade >=1 AND grade<=5 );

ALTER TABLE paymenttype ALTER COLUMN name SET UNIQUE;

ALTER TABLE payment ALTER COLUMN type_id SET NOT NULL;
ALTER TABLE payment ALTER COLUMN amount SET NOT NULL;
ALTER TABLE payment ALTER COLUMN date SET NOT NULL;